[package]
name = "crlox"
version = "0.1.0"
edition = "2018"
authors = ["Coleton O'Donnell contact@coleton.io"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "0.1.9"
substring = "1.4.5"